# -*- mode:org ; eval: (progn (visual-line-mode 0) (toggle-truncate-lines 1)) -*-
#+TITLE: Kuhsee Marathon Challenge
#+AUTHOR: Dieter Schaab
#+EMAIL:
#+DESCRIPTION: Kuhsee Marathon Challenge

#+begin_comment
(org-export-to-file 'html "../gh-pages/index.html")
#+end_comment

#+begin_comment
Countdown creation url: logwork.com/countdown-timer
Colors:
- Background #336699
- Digits Color: #ffffff
- Text Color: #bbbbbb
- Time Units Color: #bbbbbb
#+end_comment
#+BEGIN_EXPORT html
<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a
  href="https://logwork.com/countdown-1avz"
  class="countdown-timer"
  data-style="flip2"
  data-timezone="Europe/Berlin"
  data-language="de"
  data-textcolor="#bbbbbb"
  data-date="2023-12-10 10:00"
  data-background="#336699"
  data-digitscolor="#ffffff"
  data-unitscolor="#bbbbbb">6. KMC</a>
#+END_EXPORT

* Regeln 
Die grundlegenden Ideen der Kuhsee Marathon Challenge sind:
- es gibt keine Starterliste,
- es gibt kein Startgeld,
- es gibt keinen ersten und keinen letzten Läufer,
- es gibt keine Cut Offs und kein DNFs.

Jeder kann zum Start kommen, jeder kann probieren die 18 Runden zu meistern.
Und wenn es auch /nur/ 9 Runden sind, soll keiner enttäuscht sein.
Die Möglichkeit die wunderbaren (Nichtläufer sagen /die Verrückten/) Menschen kennenzulernen,
neben einem Läufer zu laufen, der schon mehrere Marathons gelaufen ist oder neben einem Marathondebütant,
nette Gespräche zu führen, zusammen die Tiefs und die Hochs zu erleben – ist einfach unbezahlbar.

* Ausschreibung 6. KMC

1. Start ist am 10.12.2023 um 9:00 am [[https://goo.gl/maps/nKrksRz24LMGqmUC6][Imbiskiosk bei den Tischtennisplatten]].
2. Ein Parkplatz (Zufahrt über die Mittenwalder Str.) ist kostenlos und in unmittelbarer Nähe zum Kiosk (100 Meter) vorhanden.
3. Die KMC gilt als gefinisht, wenn man volle 18 Runden um den Kuhsee gelaufen ist.
   Eine Runde ist ca. 2,3 km lang und man läuft insgesamt ca. 43,5km.
   Die 42 km Marke ist *kein* Finish und liegt sowieso auf der anderen Seite des Sees.
4. Die Läufer, die früher oder später fertig sind und keine Verknüpfung zu meinem Profil auf Strava oder Garmin haben,
   bitte ich, mir ein Link oder ein Screenshot von dem Ergebnis zu schicken.
5. Es gibt für alle Finisher, wie jedes Jahr, eine besondere Medaille.
   Die Kosten und das Aussehen der Medaille werden nach dem Lauf bekannt gegeben (bisher zw. 5 € und 10 €).
6. Bei der KMC ist Eigenverpflegung angesagt.
   Ein Tisch zum Abstellen des Proviants wird organisiert.
   Ein Laufrucksack ist auch eine gute Alternative.
7. Nach dem Start bilden sich auf natürliche Weise viele Laufgrüppchen.
   Achtet bitte dabei darauf, dass wir den Spaziergängern möglichst wenig Kummer bereiten.
   Die Augschburga sind ja ganz nett, aber die Grimmigen kommen auch öfter vor @@html:&#128521;@@
8. Es sind insgesamt 3 öffentliche Toiletten auf der Strecke vorhanden, wobei mindestens eine (bei der Wasserwacht) sicher auch im Winter geöffnet bleibt.
9. Bitte nimmt genug warme Sachen für "nach dem Lauf" mit.
   Erfahrungsgemäß haben wir kühleres Wetter bei der KMC @@html:&#128521;@@
10. Seit 2022 wird die KMC nach Zählordnung des [[https://www.100-marathon-club.de/][100 Marathon Club Deutschland e.V.]] durchgeführt und kann dort anerkannt werden.
11. Die digitalen Urkunden werden in der Woche nach dem Marathon per Email verschickt.
    Die Finisherliste wird gleichzeitig auf der [[https://kuhsee-marathon-challenge.github.io/kmc/][KMC Seite]] und in der Facebook Gruppe veröffentlicht.
12. Die Teilnahme erfolgt auf eigenes Risiko.
    Der Organisator übernimmt für Unfälle und Verletzungen aller Art sowie Diebstahl oder sonstige Schäden keine Haftung.
    Die Läuferinnen und Läufer versichern, dass sie gesund sind und unter Beachtung ihrer Leistungsfähigkeit am Lauf teilnehmen.
    Daten und Fotos, die im Zusammenhang mit dem Lauf stehen, können ohne Vergütungsanspruch genutzt werden.

* Geschichte
** Der 5. KMC
{{{medalr(2022)}}}
Die fünfte Edition der KMC am 11.12.2022 war wieder ein Erfolg: 1 Finisherin + 14 Finisher!

Ein weiteres Highlight der Challenge: Fabian, Peter und Michael haben KMC zu ihrem ersten Marathon gewählt und souverän abgeschlossen!

Dieses Jahr in Absprache mit 100 Marathon Club, wurde die KMC in die offizielle Liste der anerkannten Marathons aufgenommen.
Also, Marathonsammler sind willkommen!

Das sind unerwartete und sehr erfreuliche Entwicklungen des Projekts KMC.

Hiermit möchte ich JEDEM und JEDER Danke sagen: Ihr seid unglaublich und Ihr macht diesen Lauf zu etwas Besonderem!

Dank Willfried Matzke haben wir einen kleinen, aber feinen Artikel in der #AZ, so dass viele Spaziergänger uns entgegen gelächelt und gefragt haben, ob wir "/die Verrückten sind, die 18 Runden rennen wollen/". Ich freue mich auf sein Abschlussbericht in #AZ und [[https://sport-in-augsburg.de/sportnachrichten/18-runden-um-den-kuhsee-bei-kaelte-schnee-und-eis][Sport in Augsburg]]!

Eigentlich stelle ich keine Fragen am Ende der Story, werde mich aber freuen über neuen Ideen und Vorschläge für die Challenge. Was meint Ihr, was könnte die KMC noch besser und interessanter machen?

** Medaillenfotos der älteren KMC
{{{medal(2018)}}} {{{medal(2019)}}} {{{medal(2020)}}} {{{medal(2021)}}}

* Finischer
#+ATTR_HTML: :class styledtablelastrow
#+ATTR_HTML: :border 1
#+ATTR_HTML: :rules all
#+ATTR_HTML: :frame border
#+ATTR_HTML: :width 100%
| <l>        | <l>        |  <c>  | <c>  | <c>  | <c>  | <c>  | <c>  | <c>  |
| Nachname   | Vorname    | Summe | 2018 | 2019 | 2020 | 2021 | 2022 | 2023 |
|------------+------------+-------+------+------+------+------+------+------|
| Berger     | Karl-Heinz |   1   |      |      |      |      |  1   |      |
| Bischoff   | Rainer     |   1   |      |      |  1   |      |      |      |
| Einmüller  | Peter      |   2   |      |      |      |  1   |  1   |      |
| Ecker      | Fabian     |   1   |      |      |      |      |  1   |      |
| Grändorf   | Dennis     |   2   |  1   |      |  1   |      |      |      |
| Grashei    | Alexandra  |   1   |      |      |      |  1   |      |      |
| Hellmann   | Carsten    |   3   |      |  1   |  1   |  1   |      |      |
| Joos       | Stehpan    |   3   |  1   |  1   |  1   |      |      |      |
| Kaleja     | Yvonne     |   1   |      |      |      |      |  1   |      |
| Kliem      | Manfred    |   1   |      |      |  1   |      |      |      |
| Machel     | Michael    |   1   |      |      |      |      |  1   |      |
| Magg       | Christoph  |   4   |      |  1   |  1   |  1   |  1   |      |
| Mai        | Sybille    |   1   |      |      |  1   |      |      |      |
| Mielke     | Marian     |   3   |      |      |  1   |  1   |  1   |      |
| Penning    | Claudia    |   1   |      |      |      |  1   |      |      |
| Roland     | Frank      |   3   |      |      |  1   |  1   |  1   |      |
| Rupprecht  | Michael    |   1   |      |      |      |      |  1   |      |
| Safronov   | Kirill     |   1   |      |      |      |      |  1   |      |
| Schaab     | Dieter     |   5   |  1   |  1   |  1   |  1   |  1   |      |
| Schneider  | Stefan     |   1   |      |      |      |      |  1   |      |
| Utz        | Christian  |   1   |      |      |      |  1   |      |      |
| Vogel      | Simon      |   1   |      |      |      |      |  1   |      |
| Volk       | Peter      |   1   |      |      |      |      |  1   |      |
| von Hofer  | Moritz     |   2   |      |  1   |  1   |      |      |      |
| Waldow     | Maximilian |   1   |      |      |      |      |  1   |      |
| Winkelmann | Sven       |   2   |      |      |  1   |  1   |      |      |
|            |            |  45   |  3   |  5   |  12  |  10  |  15  |      |
#+tblfm: @>$3..@>$>=vsum(@<<<..@>>)::@<<<$3..@>>$3=vsum($4..$>)

* Settings                                                             :ARCHIVE:
#+OPTIONS:  H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+OPTIONS:  author:t creator:nil timestamp:t email:nil
#+OPTIONS:  arch:nil
#+OPTIONS:  html5-fancy:t
#+STARTUP:  align oddeven hideblocks
#+LANGUAGE: en
#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args :eval never-export

#+SETUPFILE: "~/.emacs.d/themes/org/default.setup"

#+MACRO: medal (eval (format "@@html:<a href=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\"><img src=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\" /></a>@@" $1))
#+MACRO: medalr (eval (format "@@html:<a href=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\" style=\"float:right\"><img src=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\" /></a>@@" $1))
