# -*- mode:org ; eval: (progn (visual-line-mode 0) (toggle-truncate-lines 1)) -*-
#+TITLE: Kuhsee Marathon Challenge
#+AUTHOR: Dieter Schaab
#+EMAIL:
#+DESCRIPTION: Kuhsee Marathon Challenge

#+begin_comment
Und der Herr sprach und sagte: Zuerst ziehe die heiligen Laufschuhe an.
Sodann sollst Du Runden zählen bis 18, nicht mehr und nicht weniger.
18 allein soll die Nummer sein, die Du zählest, und die Nummer, die Du zählest, soll 18 und nur 18 sein.
Weder sollst Du bis 19 zählen, noch sollst Du nur bis zur 17 zählen, es sei denn, dass Du fortfährst zu zählen bis zur 18.
Die 20 scheidet völlig aus.
Wenn dann die Nummer 18, welches ist die 18. Nummer von vorne, erreicht ist, dann schleudere mit Kraft Deine heiligen Laufschuhe gegen Deinen Feind.
#+end_comment

#+begin_comment
(org-export-to-file 'html "../gh-pages/index.html")
#+end_comment

#+begin_comment
Countdown creation url: logwork.com/countdown-timer
Colors:
- Background #336699
- Digits Color: #ffffff
- Text Color: #bbbbbb
- Time Units Color: #bbbbbb
#+end_comment
#+begin_comment
,#+BEGIN_EXPORT html
<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a
  href="https://logwork.com/countdown-1avz"
  class="countdown-timer"
  data-style="flip2"
  data-timezone="Europe/Berlin"
  data-language="de"
  data-textcolor="#bbbbbb"
  data-date="2023-12-10 10:00"
  data-background="#336699"
  data-digitscolor="#ffffff"
  data-unitscolor="#bbbbbb">6. KMC</a>
,#+END_EXPORT
#+end_comment

* Regeln 
Die grundlegenden Ideen der Kuhsee Marathon Challenge sind:
- es gibt keine Starterliste,
- es gibt kein Startgeld,
- es gibt keinen ersten und keinen letzten Läufer,
- es gibt keine Cut Offs und kein DNFs.

Jeder kann zum Start kommen, jeder kann probieren die 18 Runden zu meistern.
Und wenn es auch /nur/ 9 Runden sind, soll keiner enttäuscht sein.
Die Möglichkeit die wunderbaren (Nichtläufer sagen /die Verrückten/) Menschen kennenzulernen,
neben einem Läufer zu laufen, der schon mehrere Marathons gelaufen ist oder neben einem Marathondebütant,
nette Gespräche zu führen, zusammen die Tiefs und die Hochs zu erleben – ist einfach unbezahlbar.

#+begin_comment
,* Ausschreibung 6. KMC

1. Start ist am 10.12.2023 um 9:00 am [[https://goo.gl/maps/nKrksRz24LMGqmUC6][Imbiskiosk bei den Tischtennisplatten]].
2. Ein Parkplatz (Zufahrt über die Mittenwalder Str.) ist kostenlos und in unmittelbarer Nähe zum Kiosk (100 Meter) vorhanden.
3. Die KMC gilt als gefinished, wenn man volle 18 Runden um den Kuhsee gelaufen ist.
   Eine Runde ist ca. 2,3 km lang und man läuft insgesamt ca. 43,5km.
   Die 42 km Marke ist *kein* Finish und liegt sowieso auf der anderen Seite des Sees.
4. Die Läufer, die früher oder später fertig sind und keine Verknüpfung zu meinem Profil auf Strava oder Garmin haben,
   bitte ich, mir ein Link oder ein Screenshot von dem Ergebnis zu schicken.
5. Es gibt für alle Finisher, wie jedes Jahr, eine besondere Medaille.
   Die Kosten und das Aussehen der Medaille werden nach dem Lauf bekannt gegeben (bisher zw. 5 € und 10 €).
6. Bei der KMC ist Eigenverpflegung angesagt.
   Ein Tisch zum Abstellen des Proviants wird organisiert.
   Ein Laufrucksack ist auch eine gute Alternative.
7. Nach dem Start bilden sich auf natürliche Weise viele Laufgrüppchen.
   Achtet bitte dabei darauf, dass wir den Spaziergängern möglichst wenig Kummer bereiten.
   Die Augschburga sind ja ganz nett, aber die Grimmigen kommen auch öfter vor @@html:&#128521;@@
8. Es sind insgesamt 3 öffentliche Toiletten auf der Strecke vorhanden, wobei mindestens eine (bei der Wasserwacht) sicher auch im Winter geöffnet bleibt.
9. Bitte nimmt genug warme Sachen für "nach dem Lauf" mit.
   Erfahrungsgemäß haben wir kühleres Wetter bei der KMC @@html:&#128521;@@
10. Seit 2022 wird die KMC nach Zählordnung des [[https://www.100-marathon-club.de/][100 Marathon Club Deutschland e.V.]] durchgeführt und kann dort anerkannt werden.
11. Die digitalen Urkunden werden in der Woche nach dem Marathon per Email verschickt.
    Die Finisherliste wird gleichzeitig auf der [[https://kuhsee-marathon-challenge.github.io/kmc/][KMC Seite]] und in der Facebook Gruppe veröffentlicht.
12. Die Teilnahme erfolgt auf eigenes Risiko.
    Der Organisator übernimmt für Unfälle und Verletzungen aller Art sowie Diebstahl oder sonstige Schäden keine Haftung.
    Die Läuferinnen und Läufer versichern, dass sie gesund sind und unter Beachtung ihrer Leistungsfähigkeit am Lauf teilnehmen.
    Daten und Fotos, die im Zusammenhang mit dem Lauf stehen, können ohne Vergütungsanspruch genutzt werden.
#+end_comment

* Geschichte
** Der 6. KMC
{{{medalr(2023)}}}
Die sechste Edition der KMC am 10.12.2023... ein Großereignis der Superlative, stand unter dem Motto:
#+begin_center
*Ob 18, 42 oder 100 – es ist nur eine Zahl im Kopf* [fn:: Ein "berühmter Spruch" von Grändorf Dennis, der KMC mitgegründet und 2018 und 2020 auch gefinished hat.]!
#+end_center

Was ja alle schon ahnten, Dieter konnte erfolgreich seinen hundertsten Marathon laufen und ist nun offiziell stolzes Vollmitglied im [[https://www.100-marathon-club.de/][100 Marathon Club Deutschland e.V.]].
Viele haben mitgeholfen, ein besonders Finale vorzubereiten, sogar das Wetter hat an diesem Sonntag gut mitgespielt.
Bei Temperaturen im hohen einstelligen Bereich ließ sich die Sonne immer wieder zwischen den Wolken blicken und bescherte Dieter punktgenau einen Zieleinlauf unter blauem Himmel.
Bei musikalischer AC/DC Untermalung und eingerahmt von zwei Leuchtfackeln lief Dieter durch das Zielband und nahm einen Pokal, die @@html:&#128175;@@ MC Medaille und das gelbe Mitgliederband in Empfang.

#+begin_center
{{{image_size(kmc6/dieter-finish.jfif, 800)}}}
#+end_center

{{{image_size_r(kmc6/kuchen.jfif, 200)}}}
Besonders schön war, dass auch Dieters Familie mitgefeiert hat und er von seiner Frau, den Kindern und Eltern im Ziel empfangen wurde.
Vor allem diese Unterstützung macht so ein Erfolg erst möglich.

Abschließend wurde dieser grandiose Meilenstein in Dieters leidenschaftlichem Läuferleben mit Kuchen (dank Sybille), Sekt und Bier gemeinsam gefeiert.
An dieser Stelle noch mal: Herzlichen Glückwunsch Dieter zu dieser phänomenalen Leistung.
\\
\\
\\
\\

Das war natürlich noch längst nicht alles. Es haben sich auch weitere Berühmtheiten dazugesellt. {{{image_size_r(kmc6/michael-turzynski.jfif, 200)}}}
So waren die lokalen Marathonlegenden Udo Pitsch, der schon [[https://statistik.d-u-v.org/getresultperson.php?runner=13878][118 bei DUV gelistete Ultras]] und über 285 Marathons lief, sowie Bernie Manhard ([[https://www.team-tomj.de/runner.htm#bernie][119 Marathons, 55 Ultras]]) und Charly Berger ([[https://www.team-tomj.de/runner.htm#charly][115 Marathons und 10 Ultras]]) mit dabei.
Aber auch [[https://www.runwithviktor.de/][Viktor Reger]], der sich anschickt 365 Ultramarathon in einem Jahr zu laufen und es damit auf 18250 km bringen will, ist [[https://www.instagram.com/p/C0rqeaerzmk/][ein Stück mit uns gelaufen]].
Und nicht zu vergessen Michael Turzynski aus Hannover, ein Mitbegründer des [[https://www.100-marathon-club.de/][100 Marathon Club Deutschland e.V.]] der sich das Ziel gesetzt hat 1000 Marathons zu laufen und beim 6. KMC seien 945-ten absolviert hat.

Wir hatten sogar zwei Marathon Debüts: Alexandra Greishei hat ihren ersten offiziellen Marathon gefinished (davor nur virtuelle) und Sebastian Mittomayer hat überhaupt seinen ersten Marathon gelaufen.

Mit einem Sprung ins Wasser haben sich Yvonne Kaleja und Frank Roland abgekühlt und das Eis des Kuhsees gebrochen.

Dieser Lauf ist mit insgesamt 25 Finishern, davon fünf Frauen, mit Abstand der teilnehmerstärkste Lauf bisher.
Das Publikum war stark wie nie und hat mit Ratschen, Kuhglocken @@html:&#128276;@@ läuten und Anfeuerungen für Stimmung gesorgt.
Einen besonderen Dank an Peter Volk, der die Kuhglocke bereitgestellt und für zukünftige Veranstaltungen gespendet hat, an Simon Volk, für die Fackeln und den Pokal, an Yvonne Kaleja, die das Zielband gestaltet hat, und an Stefan Joos, der für die Musik gesorgt hat.
Ein großes Lob auch an jeden, der dabei war und mitgelaufen ist, egal wie viele Runden: Ihr habt super durchgehalten, auch wenn manche Stellen auf der Strecke vereist waren.

#+begin_center
{{{image_size(kmc6/runner.jfif, 800)}}}
#+end_center

Wer noch mehr erfahren möchte, Wilfried Matzke hat einen Artikel in [[https://sport-in-augsburg.de/sportnachrichten/18-runden-im-laufschritt-um-den-kuhsee][Sport in Augsburg]] verfasst.

** Der 5. KMC
{{{medalr(2022)}}}
Die fünfte Edition der KMC am 11.12.2022 war wieder ein Erfolg: 1 Finisherin + 14 Finisher!

Ein weiteres Highlight der Challenge: Fabian, Peter und Michael haben KMC zu ihrem ersten Marathon gewählt und souverän abgeschlossen!

Dieses Jahr in Absprache mit 100 Marathon Club, wurde die KMC in die offizielle Liste der anerkannten Marathons aufgenommen.
Also, Marathonsammler sind willkommen!

Das sind unerwartete und sehr erfreuliche Entwicklungen des Projekts KMC.

Hiermit möchte ich JEDEM und JEDER Danke sagen: Ihr seid unglaublich und Ihr macht diesen Lauf zu etwas Besonderem!

Dank Willfried Matzke haben wir einen kleinen, aber feinen Artikel in der #AZ, so dass viele Spaziergänger uns entgegen gelächelt und gefragt haben, ob wir "/die Verrückten sind, die 18 Runden rennen wollen/". Ich freue mich auf seinen Abschlussbericht in #AZ und [[https://sport-in-augsburg.de/sportnachrichten/18-runden-um-den-kuhsee-bei-kaelte-schnee-und-eis][Sport in Augsburg]]!

Eigentlich stelle ich keine Fragen am Ende der Story, werde mich aber freuen über neuen Ideen und Vorschläge für die Challenge. Was meint Ihr, was könnte die KMC noch besser und interessanter machen?

** Medaillenfotos der älteren KMC
#+begin_center
{{{medal(2018)}}} {{{medal(2019)}}} {{{medal(2020)}}} {{{medal(2021)}}}
#+end_center

* Finisher
#+ATTR_HTML: :class styledtablelastrow
#+ATTR_HTML: :border 1
#+ATTR_HTML: :rules all
#+ATTR_HTML: :frame border
#+ATTR_HTML: :width 100%
| <l>          | <l>        |  <c>  | <c>  | <c>  | <c>  | <c>  | <c>  | <c>  |
| Nachname     | Vorname    | Summe | 2018 | 2019 | 2020 | 2021 | 2022 | 2023 |
|--------------+------------+-------+------+------+------+------+------+------|
| Berger       | Karl-Heinz |   2   |      |      |      |      |  1   |  1   |
| Bischoff     | Rainer     |   1   |      |      |  1   |      |      |      |
| Ecker        | Fabian     |   1   |      |      |      |      |  1   |      |
| Einmüller    | Peter      |   3   |      |      |      |  1   |  1   |  1   |
| Gamperl      | Elisabeth  |   1   |      |      |      |      |      |  1   |
| Grashei      | Alexandra  |   2   |      |      |      |  1   |      |  1   |
| Grändorf     | Dennis     |   2   |  1   |      |  1   |      |      |      |
| Hellmann     | Carsten    |   3   |      |  1   |  1   |  1   |      |      |
| Jetzlsperger | Klaus      |   1   |      |      |      |      |      |  1   |
| Joos         | Stehpan    |   3   |  1   |  1   |  1   |      |      |      |
| Kaleja       | Yvonne     |   2   |      |      |      |      |  1   |  1   |
| Kliem        | Manfred    |   1   |      |      |  1   |      |      |      |
| Klinger      | Thomas     |   1   |      |      |      |      |      |  1   |
| Machel       | Michael    |   2   |      |      |      |      |  1   |  1   |
| Magg         | Christoph  |   5   |      |  1   |  1   |  1   |  1   |  1   |
| Manhard      | Bernie     |   1   |      |      |      |      |      |  1   |
| Mai          | Sybille    |   1   |      |      |  1   |      |      |      |
| Mayr         | Richard    |   1   |      |      |      |      |      |  1   |
| Mielke       | Marian     |   3   |      |      |  1   |  1   |  1   |      |
| Mittomayer   | Bastian    |   1   |      |      |      |      |      |  1   |
| Nagl         | Melanie    |   1   |      |      |      |      |      |  1   |
| Nashilevskiy | Alexander  |   1   |      |      |      |      |      |  1   |
| Neumann      | Conni      |   1   |      |      |      |      |      |  1   |
| Penning      | Claudia    |   1   |      |      |      |  1   |      |      |
| Pitsch       | Udo        |   1   |      |      |      |      |      |  1   |
| Roland       | Frank      |   4   |      |      |  1   |  1   |  1   |  1   |
| Rupprecht    | Michael    |   2   |      |      |      |      |  1   |  1   |
| Safronov     | Kirill     |   2   |      |      |      |      |  1   |  1   |
| Schaab       | Dieter     |   6   |  1   |  1   |  1   |  1   |  1   |  1   |
| Schneider    | Stefan     |   2   |      |      |      |      |  1   |  1   |
| Turzynski    | Michael    |   1   |      |      |      |      |      |  1   |
| Utz          | Christian  |   2   |      |      |      |  1   |      |  1   |
| Vogel        | Simon      |   2   |      |      |      |      |  1   |  1   |
| Volk         | Peter      |   1   |      |      |      |      |  1   |      |
| Waldow       | Maximilian |   1   |      |      |      |      |  1   |      |
| Winkelmann   | Sven       |   2   |      |      |  1   |  1   |      |      |
| Zischke      | Mathias    |   1   |      |      |      |      |      |  1   |
| von Hofer    | Moritz     |   2   |      |  1   |  1   |      |      |      |
|              |            |  70   |  3   |  5   |  12  |  10  |  15  |  25  |
#+tblfm: @>$3..@>$>=vsum(@<<<..@>>)::@<<<$3..@>>$3=vsum($4..$>)

* Settings                                                             :ARCHIVE:
#+OPTIONS:  H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc
#+OPTIONS:  author:t creator:nil timestamp:t email:nil
#+OPTIONS:  arch:nil
#+OPTIONS:  html5-fancy:t
#+STARTUP:  align oddeven hideblocks
#+LANGUAGE: en
#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args :eval never-export

#+SETUPFILE: "~/.emacs.d/themes/org/default.setup"

#+MACRO: medal (eval (format "@@html:<a href=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\"><img src=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\" /></a>@@" $1))
#+MACRO: medalr (eval (format "@@html:<a href=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\" style=\"float:right\"><img src=\"images/medals/%1$s.jpg\" alt=\"Medaille %1$s\" title=\"Medaille %1$s\" width=\"200px\" /></a>@@" $1))
#+MACRO: image_size (eval (format "@@html:<a href=\"images/%1$s\" alt=\"%1$s\" width=\"%2$s\"><img src=\"images/%1$s\" alt=\"%1$s\" width=\"%2$s\" /></a>@@" $1 $2))
#+MACRO: image_size_r (eval (format "@@html:<a href=\"images/%1$s\" alt=\"%1$s\" width=\"%2$s\" style=\"float:right\"><img src=\"images/%1$s\" alt=\"%1$s\" width=\"%2$s\" /></a>@@" $1 $2))
