* Notizen
- url: https://kuhsee-marathon-challenge.github.io/kmc/

- Race Results Anmeldung:
  - 2025: https://my.raceresult.com/341874/registration

** Tabelle
Ich habe die folgenden Felder hinzugefügt (~Hauptfenster~ \to ~Teilnehmerdaten~ \to ~Zusatzfelder~):
| Type     | Name             |                      |                                            |
|----------+------------------+----------------------+--------------------------------------------|
| Checkbox | Warteliste       | 0: normale Anmeldung | 1: Auf Warteliste                          |
| Checkbox | MedailleBezahlt  | 0: offen             | 1: bezahlt                                 |
| Datum    | MedailleErhalten | nicht erhalten       | Datum, an dem die Medaille übergeben wurde |
| Checkbox | Absage           | 0: keine Absage      | 1: Absage durch Läufer                     |
| Checkbox | Frühstarter      | 0: kein Frühstarter  | 1: Frühstarter                             |

Im Menü ~Teilnehmer~ findet man nun bei den Teilnehmer unten ~INFORMATIONEN~ und dort Checkboxen bzw. Eingabemasken für die neuen Felder.

** Formulare
Es gibt zwei Anmeldeformulare, für eine ~Einzel-Anmeldung~ bis 50 Teilnehmer und eine für die ~Wartelisten-Anmeldung~ bis 100 Teilnehmer (~Hauptfenster~ \to ~Anmelde-Formulare~).

Bei der ~Wartelisten-Anmeldung~ wird unter ~Aktionen nach Speichern~ das Feld ~Warteliste~ automatisch auf ~1~ gesetzt.

Unter ~my.raceresults.com~ \to ~Seite "Anmeldung"~ \to ~ANMELDE-FORMULARE~ kann die ~Wartelisten-Anmeldung~ hinzugefügt werden, sobald die maximale Teilnehmerzahl der ~Einzel-Anmeldung~ erreicht ist.

** Ausgabe
Über das Menü ~Ausgabe~ \to ~ONLINE~ findet man die Einstellungen für Online Tabellenübersichten.
Man kann sich die Tabellenausgaben unter ~Ansicht~ anzeigen lassen oder herunterladen.
- Unter ~Teilnehmer Kurz~ kann konfiguriert werden, welche Teilnehmer angezeigt werden.
  Hier muss man die Felder ~Warteliste~ und ~Absage~ auf ~0~ prüfen.
- Unter ~Warteliste Kurz~ findet man alle Teilnehmer, die in der Warteliste stehen.
- Unter ~Absagen Kurz~ findet man alle abgesagten Teilnehmer.

Im Menü ~Ausgabe~ \to ~TEILNEHMERLISTEN~ sind folgende Ausgaben definiert:
- ~Meldeliste ABC~: Alle gemeldeten Teilnehmer alphabetischer Reihenfolge.
- ~Teilnehmerliste 123~: Alle Teilnehmer die nicht abgemeldet sind und nicht auf der Warteliste stehen in numerischer Reihenfolge.
- ~Nicht-Teilnehmerliste 123~: Alle Teilnehmer die abgemeldet sind oder auf der Warteliste stehen in numerischer Reihenfolge.
- ~Teilnehmerliste RB~: definiert eine Abfrageliste, z.B. für Ruby.
  Dazu ist diese Liste unter ~Hauptfenster~ \to ~Zugriffsrechte/Freigabe~ \to ~FREIGABE (SIMPLEAPI)~ freigegeben als:
  - Typ: Liste
  - Details: Teilnehmerliste RB
  - JSON ext
  Mit einem Klick auf ~Link~ werden die JSON-Daten und der benötigte Link angezeigt.

** Warteliste

Die Teilnehmer mit eine BIB <= 50 hatten sich regulär angemeldet, ab BIB 51 über die Warteliste. Letztere haben das Feld ~Warteliste~ auf ~1~.

Sobald ein Teilnehmer absagt wird das Feld ~Absage~ auf ~1~ gesetzt.

Mit dem Skript ~nachruecken.rb~ kann ermittelt werden, wer als Ersatz übernommen werden kann:
#+begin_src sh :exports result :results output
ruby nachruecken.rb
#+end_src

** Mail-Templates
*** Abmeldung
Wegen Krankheit:
#+begin_example
Hallo,

vielen Dank für Deine Nachricht – sehr schade, dass Du dieses Jahr nicht dabei sein kannst! Wir haben Dich wie gewünscht aus der Teilnehmerliste ausgetragen.

Für Deine Gesundheit wünschen wir Dir alles Gute und eine schnelle, vollständige Genesung. Wir würden uns sehr freuen, Dich 2026 am Start zu sehen!

Sportliche Grüße
Das KMC Orga-Team
#+end_example

Wegen Zeit:
#+begin_example
Hallo,

vielen Dank für Deine Nachricht – sehr schade, dass Du dieses Jahr nicht dabei sein kannst! Wir haben Dich wie gewünscht aus der Teilnehmerliste ausgetragen.

Wir würden uns sehr freuen, Dich 2026 am Start zu sehen!

Sportliche Grüße
Das KMC Orga-Team
#+end_example
*** KMC Nachrückung
#+begin_example
Servus,

gute Nachrichten: Du bist von der Warteliste in die Teilnehmerliste nachgerückt – willkommen bei der Kuhsee Marathon Challenge! 🎉

Wir freuen uns sehr, dass Du dabei bist und wünschen Dir viel Spaß bei der Vorbereitung. Falls Du noch Fragen hast, melde Dich jederzeit gerne.

Sportliche Grüße
Frank
#+end_example
*** Anmeldung
#+begin_example
Hallo,

vielen Dank für deine Nachricht – wie schön, dass du unsere Challenge entdeckt hast und Interesse hast, 2026 mitzulaufen!
Die Anmeldung für 2025 ist tatsächlich bereits voll, aber du kannst dich gerne auf die Warteliste für 2025 setzen. Falls kurzfristig Plätze frei werden, melden wir uns direkt bei dir.
Für die Kuhsee Marathon Challenge 2026 startet die Anmeldung voraussichtlich Mitte 2026. Den genauen Termin geben wir rechtzeitig bekannt – entweder über unsere Facebook-Gruppe, im Strava KMC Club oder direkt auf der KMC-Webseite.
Wenn ihr dort mit dabei seid, verpasst ihr nichts – und wir würden uns sehr freuen, euch nächstes Jahr am Start zu sehen!

Sportliche Grüße
Das KMC Orga-Team
#+end_example
